//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Construction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Construction()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id_constr { get; set; }
        public Nullable<int> Id_model { get; set; }
        public Nullable<int> Id_color { get; set; }
        public string Name { get; set; }
        public Nullable<int> HorsePower { get; set; }
        public string Transmission { get; set; }
        public Nullable<double> EngineCapacity { get; set; }
        public string Drive { get; set; }
        public string EngineType { get; set; }
        public Nullable<int> InStock { get; set; }
    
        public virtual Colour Colour { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
