//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_order { get; set; }
        public Nullable<int> Id_client { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> Id_adm { get; set; }
        public Nullable<int> Id_status { get; set; }
        public Nullable<int> Id_product { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Administration Administration { get; set; }
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
    }
}
